const storeKeys = {
  APP_GLOBALCONFIGS: 'APP_GLOBALCONFIGS',
  APP_DEVICEINFO: 'APP_DEVICEINFO',
  USER_INFO: 'USER_INFO',

  STORAGE_APPINFO: 'STORAGE_APPINFO',
  STORAGE_LOGIN_STATUS: 'STORAGE_LOGIN_STATUS',
};

export default storeKeys;
